logging: 
  config: classpath:logback-dev.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: developer
    url: jdbc:mysql://111.230.9.229/ss_test?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: developer
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  mail:
    host: smtp.starrysea.top
    password: Xingzhihai2017
    port: '25'
    properties:
      mail:
        smtp:
          auth: 'true'
    username: mumuzhizhi@starrysea.top
  mvc:
    favicon:
      enabled: 'false'
  thymeleaf:
    cache: 'false'
    mode: LEGACYHTML5
    servlet:
      content-type: text/html
  redis:
    host: 111.230.9.229
    port: 6379
    password: root1
    jedis:
      pool:
        max-active: 8
        max-wait: 1800
        max-idle: 8
        min-idle: 0
    timeout: 0 
  banner:
    charset: UTF-8
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown
ss:
  fileroot: D:/develop/nginx-1.12.1/
payelves:
  gateway:  https://www.payelves.com/api/v1/pay/web
  openId: AWLg6Cj3d
  token:  8216e8aebcd143f590abf996f14e29fe
  uuid: yeah-Tiger
  clientVersion:  3.3.0
  appKey: 8097732829315073